# Generated by Django 4.2.11 on 2026-06-20 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeRoom',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, help_text="Unique room identifier, e.g. 'room-a982f1'", max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Shared Workspace Document.md', max_length=255)),
                ('content', models.TextField(blank=True, default='# Shared Document Markdown\n')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestPresence',
            fields=[
                ('peer_id', models.CharField(help_text='Random peer session token generated on the client', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Peer Guest', max_length=150)),
                ('color_class', models.CharField(default='bg-indigo-600', max_length=50)),
                ('avatar_style', models.CharField(default='shapes', help_text='Avatar style: shapes | bottts | lorelei | pixel-art | initials | adventurer', max_length=50)),
                ('last_pulse', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='rooms.collaborativeroom')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('updated_by_name', models.CharField(default='Anonymous Peer', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='rooms.collaborativeroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
