# Generated by Django 4.2.11 on 2026-06-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeroom',
            name='is_live',
            field=models.BooleanField(default=True, help_text="When False, the room's link is revoked — no new WebSocket connections are accepted and existing ones are force-closed."),
        ),
    ]
