# Generated by Django 4.2.11 on 2026-06-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_collaborativeroom_is_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('browser', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('operating_system', models.CharField(blank=True, default='Unknown', max_length=50)),
                ('device_type', models.CharField(blank=True, default='Desktop', max_length=20)),
                ('path', models.CharField(blank=True, default='/', max_length=255)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('visitor_id', models.CharField(blank=True, db_index=True, default='', help_text="Client-generated id stored in the browser's localStorage — used to approximate unique visitors (not a real identity).", max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
